// Code generated by ogen, DO NOT EDIT.

package api

import (
	"net/http"

	"github.com/ogen-go/ogen/validate"
)

func decodeOnboardResponse(resp *http.Response) (res OnboardRes, _ error) {
	switch resp.StatusCode {
	case 200:
		// Code 200.
		return &OnboardOK{}, nil
	case 401:
		// Code 401.
		return &OnboardUnauthorized{}, nil
	case 403:
		// Code 403.
		return &OnboardForbidden{}, nil
	}
	return res, validate.UnexpectedStatusCode(resp.StatusCode)
}
