
{{- if .Values.serviceAccount.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "onyxia-onboarding.fullname" . }}
  labels:
    {{- include "onyxia-onboarding.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.serviceAccount.existingClusterRole }}
subjects:
- kind: ServiceAccount
  name: {{ include "onyxia-onboarding.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end -}}
