// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
)

// OnboardingRequest Specification on which namespace to create
type OnboardingRequest struct {
	Group *string `json:"group,omitempty"`
}

// OnboardJSONRequestBody defines body for Onboard for application/json ContentType.
type OnboardJSONRequestBody = OnboardingRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Init a user or a group
	// (POST /onboarding)
	Onboard(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// Init a user or a group
// (POST /onboarding)
func (_ Unimplemented) Onboard(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// Onboard operation middleware
func (siw *ServerInterfaceWrapper) Onboard(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Onboard(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/onboarding", wrapper.Onboard)
	})

	return r
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/3xVwW4cNw9+FUL/fxzPOk1Pe0tSFDV6SJE0yKHIgStxZhhrSEXS7HgbGOhD9An7JAU1",
	"u7ZbBz3tLEWR/Ph9pL46r3NSIanF7b+64ieasX2+lYNiDizjO/qyUKlmDFR85lRZxe3d+0SeB/Zo/0EF",
	"1on9BIIzlYSeoCr4TFjJdS5lTZQrU4s+Zl2SfdRTIrd3pWaW0d3fdxeLHj6Tr81SyC+Z6+m9Vbfdx6VO",
	"9quJ5Ca8URHy9UOObu+mWlPZ73bm0kc89KUkH3UJ/ZCbcZcJ41x2F/uuXynGq1vRVXYWkMOVVxl4XHKD",
	"5h6LeprO3VtxLIM+b81j9+DVLzfABQIVHoWCNSXTjCwws/CMsYORj+ZJ6Cd4K6c7RmApFcV6OBEMke74",
	"wJHrya4vxcxcoFA+sifQDCnrkQMB1wK6Sg83FTAWBYxR1wIYWjEDYV0yFSiLnwALfFm0IswoONJMUnt4",
	"fYJCCQ26jFsegzBknVsxXjPBsIg3qBjZKO1AW9lXKx1gXkqFCSVEArqrGSHqyP6vP/5cJPLtBillOrIu",
	"hqEuqYN1okxPpNN0Y7JasUDhSFLjCRLlQfNMAQ6nFkZjoGz19fCqAm4tXeYOVgKhrduBBhYCFCAJSVkq",
	"sDxAuXpoiaGsCkfKPGzR6Y5LJWNBB8An1R3Io7GgjzRzAW3sC8beFMM1Nsk8uFxhYhg0A0KmcdPVkXLZ",
	"FPOiv+6v3X3XNIaJ3d697K/7FzY6WKem+t1jMPub9FtT+asx9oB0Y7aYDKBiuS1PerhOJIAmp2wUFWCp",
	"2oBv9TURbUSWrV8XUjTDkgLWfzemA4wqI6xcJ5ipYsBqWraE7WYHhWeOmOGcyS85k9TW/ANNeGTN0FTS",
	"lNnDR4Iy6RLDJmevUtg4XyeqE7U4NkwVz5w+BNHhXK+MgPBOI71m2YZAc3N9e/PDm4a+h48Tx8tQLSlp",
	"rsW0S1kwttps1CiDxxhLB1yNb9F61jLPmE8wKkZLu41wU6QdHymfIBKW2m0ZHko8A7M4BwISPMRN2oEG",
	"XGLt4Sdd6Ui56dmjQKYGFOUsNoNPdymyZ5uPbdtuWZ4i5qFNAwVTpu3hRsZNeNxUrnN52/OvNZxMVV6l",
	"kjSBYbIM7c7uczGVXZ4K+/p/psHt3f92j2/J7vyQ7J6/Im1pWirOFNy+5oWaoSSVsi33766vv7FRf7bh",
	"+P76xfOjD2JrXTP/TmFzevnc6UfNBw6BZHtSltkoc3t3I1wvQ9Bmc3uaOldxLG7/25NV7j614s8H/7Hy",
	"M0WsFC77ubjO2Yj8w8ndf7r/OwAA//8rWq5CfwcAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
