name: Publish Helm Chart

on:
  push:
    branches:
      - main
    paths:
      - "deploy/**" # Trigger only when Helm chart changes

permissions:
  contents: read
  packages: write

jobs:
  deploy-helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Helm
        uses: azure/setup-helm@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Package Helm chart
        run: |
          helm package deploy/ --destination ./deploy/release

      - name: Push Helm chart to Docker Hub
        run: |
          CHART_NAME=$(ls deploy/release | grep .tgz | head -n 1)
          helm push deploy/release/$CHART_NAME oci://docker.io/${{ secrets.DOCKERHUB_USERNAME }}
